language: node_js
cache:
  yarn: true
  directories: ["node_modules"]
node_js:
  - "lts/*"
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
before_cache:
  - rm -rf node_modules/.cache
script: yarn test --coverage
after_success: node ./node_modules/.bin/coveralls < ./coverage/lcov.info
